# Generated by Django 4.2.3 on 2023-08-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Angelinus",
            fields=[
                ("num", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=25)),
                ("addr1", models.CharField(max_length=40)),
                ("addr2", models.CharField(max_length=40)),
                ("addrx", models.CharField(blank=True, max_length=40, null=True)),
                ("addry", models.CharField(blank=True, max_length=40, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("star", models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                "db_table": "angelinus",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Burgerking",
            fields=[
                ("num", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=25)),
                ("addr1", models.CharField(max_length=40)),
                ("addr2", models.CharField(max_length=40)),
                ("addrx", models.CharField(blank=True, max_length=40, null=True)),
                ("addry", models.CharField(blank=True, max_length=40, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("star", models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                "db_table": "burgerking",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Ediya",
            fields=[
                ("num", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=25)),
                ("addr1", models.CharField(max_length=40)),
                ("addr2", models.CharField(max_length=40)),
                ("addrx", models.CharField(blank=True, max_length=40, null=True)),
                ("addry", models.CharField(blank=True, max_length=40, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("star", models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                "db_table": "ediya",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Hollys",
            fields=[
                ("num", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=25)),
                ("addr1", models.CharField(max_length=40)),
                ("addr2", models.CharField(max_length=40)),
                ("addrx", models.CharField(blank=True, max_length=40, null=True)),
                ("addry", models.CharField(blank=True, max_length=40, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("star", models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                "db_table": "hollys",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Kfc",
            fields=[
                ("num", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=25)),
                ("addr1", models.CharField(max_length=40)),
                ("addr2", models.CharField(max_length=40)),
                ("addrx", models.CharField(blank=True, max_length=40, null=True)),
                ("addry", models.CharField(blank=True, max_length=40, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("star", models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                "db_table": "kfc",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Lotteria",
            fields=[
                ("num", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=25)),
                ("addr1", models.CharField(max_length=40)),
                ("addr2", models.CharField(max_length=40)),
                ("addrx", models.CharField(blank=True, max_length=40, null=True)),
                ("addry", models.CharField(blank=True, max_length=40, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("star", models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                "db_table": "lotteria",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Mcdonalds",
            fields=[
                ("num", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=25)),
                ("addr1", models.CharField(max_length=40)),
                ("addr2", models.CharField(max_length=40)),
                ("addrx", models.CharField(blank=True, max_length=40, null=True)),
                ("addry", models.CharField(blank=True, max_length=40, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("star", models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                "db_table": "mcdonalds",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Pascucci",
            fields=[
                ("num", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=25)),
                ("addr1", models.CharField(max_length=40)),
                ("addr2", models.CharField(max_length=40)),
                ("addrx", models.CharField(blank=True, max_length=40, null=True)),
                ("addry", models.CharField(blank=True, max_length=40, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("star", models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                "db_table": "pascucci",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Starbucks",
            fields=[
                ("num", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=25)),
                ("addr1", models.CharField(max_length=40)),
                ("addr2", models.CharField(max_length=40)),
                ("addrx", models.CharField(blank=True, max_length=40, null=True)),
                ("addry", models.CharField(blank=True, max_length=40, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("star", models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                "db_table": "starbucks",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Twosomeplace",
            fields=[
                ("num", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=25)),
                ("addr1", models.CharField(max_length=40)),
                ("addr2", models.CharField(max_length=40)),
                ("addrx", models.CharField(blank=True, max_length=40, null=True)),
                ("addry", models.CharField(blank=True, max_length=40, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("star", models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                "db_table": "twosomeplace",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Thru",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
