# Generated by Django 4.1 on 2023-08-24 11:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("thru", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="twosomeplace",
            table="twosome",
        ),
    ]
